### ISSUE TITLE
TestLayout test failes

### ISSUE THREAD

**Issue by zabulus** [RazorGenerator/RazorGenerator#10]
Here is failure message
```
Test Name:	TestLayout
Test FullName:	MvcViewsTests.TestViews.TestLayout
Test Source:	e:\Workshop\RazorGenerator\MvcViewsTests\TestViews.cs : line 71
Test Outcome:	Failed
Test Duration:	0:00:00,0726103

Result Message:	
Test method MvcViewsTests.TestViews.TestLayout threw exception: 
System.Web.HttpException: The file "" cannot be requested directly because it calls the "RenderBody" method.
Result StackTrace:	
at System.Web.WebPages.WebPageBase.RenderBody()
   at PrecompiledMvcLibrary.Views.Shared._Layout.Execute() in d:\forks\razorsinglefilegenerator\samples\precompiledmvclibrary\views\shared\_Layout.cshtml:line 32
   at RazorGenerator.Testing.WebViewPageExtensions.Render[TModel](WebViewPage`1 view, HttpContextBase httpContext, TModel model) in e:\Workshop\RazorGenerator\RazorGenerator.Testing\WebViewPageExtensions.cs:line 55
   at RazorGenerator.Testing.WebViewPageExtensions.Render[TModel](WebViewPage`1 view, TModel model) in e:\Workshop\RazorGenerator\RazorGenerator.Testing\WebViewPageExtensions.cs:line 29
   at MvcViewsTests.TestViews.TestLayout() in e:\Workshop\RazorGenerator\MvcViewsTests\TestViews.cs:line 81
```

**Comment by davidebbo** [comment]
I know, it's been failing forever :( I actually disabled it yesterday before pointing you to the tests. https://github.com/RazorGenerator/RazorGenerator/commit/07b3e669380ac6240e09eb0c0f85d7edff69c506
