### ISSUE TITLE
Unable to install extension in Visual Studio 2013

### ISSUE THREAD

**Issue by Elimi81** [RazorGenerator/RazorGenerator#137]
Hi!

I'v used RazorGenerator in the past but now after new PC I'm unable to install the needed extension to Visual Studio 2013:
![image](https://cloud.githubusercontent.com/assets/25981370/23259823/9b2645a8-f9d7-11e6-936b-f64a26a8a4e5.png)

The extension can not be found in the "Extensions ans Updates" search:
![image](https://cloud.githubusercontent.com/assets/25981370/23259859/d467b900-f9d7-11e6-8d4e-2440da429d6b.png)

And when I try to manually install the extension it says "This extension is not installable on any currently installed products":
![image](https://cloud.githubusercontent.com/assets/25981370/23259887/faeb2ce2-f9d7-11e6-9ef9-a5701095bd52.png)

Log:
23.2.2017 14.53.47 - Microsoft VSIX Installer
23.2.2017 14.53.47 - -------------------------------------------
23.2.2017 14.53.48 - Initializing Install...
23.2.2017 14.53.48 - Extension Details...
23.2.2017 14.53.48 - 	Identifier      : 2FD58EB3-29A2-40A3-BE17-C024CA9A17A2
23.2.2017 14.53.48 - 	Name            : Razor Generator
23.2.2017 14.53.48 - 	Author          : RazorGenerator contributors
23.2.2017 14.53.48 - 	Version         : 1.11.0
23.2.2017 14.53.48 - 	Description     : Generates source code from Razor files (.cshtml/.vbhtml files), allowing them to be compiled into your assemblies. Supports MVC, Web Pages and standalone templates.
23.2.2017 14.53.48 - 	Locale          : en-US
23.2.2017 14.53.48 - 	MoreInfoURL     : https://github.com/RazorGenerator/RazorGenerator
23.2.2017 14.53.48 - 	InstalledByMSI  : False
23.2.2017 14.53.48 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
23.2.2017 14.53.48 - 
23.2.2017 14.53.48 - 	Supported Products : 
23.2.2017 14.53.48 - 		Microsoft.VisualStudio.Community
23.2.2017 14.53.48 - 			Version : [11.0,16.0)
23.2.2017 14.53.48 - 
23.2.2017 14.53.48 - 	References      : 
23.2.2017 14.53.48 - 
23.2.2017 14.53.48 - Searching for applicable products...
23.2.2017 14.53.49 - Found installed product - Microsoft Visual Studio Professional 2013
23.2.2017 14.53.49 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
23.2.2017 14.53.49 - Found installed product - Global Location
23.2.2017 14.53.49 - Found installed product - ssms
23.2.2017 14.53.49 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

What is the cause of this? Has something changed in the extension? I tried my old machine and uninstalled the extension (did not remember to check the version I had previously :( ) and tried to install the extension again and it also failed. So I suspect that some older version of the extension worked and the new one doesn't.

Any help?

**Comment by davidebbo** [comment]
Not sure why it doesn't show up for VS 2013. It shows up correctly for 2015/2017.

I just created a new release for 1.11.0, so try installing the VSIX directly from there (https://github.com/RazorGenerator/RazorGenerator/releases). I just tried and it worked fine for my 2013.

**Comment by sfu11** [comment]
I experienced same issue on VS2012.
However, I managed to install version 1.10.1 successfully.

**Comment by Elimi81** [comment]
Thank you for your response. The version 1.11.0 is exactly the version I was trying to install and it does not work. Which version of VS 2013 do you have? Do you have update 5 installed?

I now tried installing the version 1.10.1 and it works fine. So there is something "wrong" with the 1.11.0.

**Comment by Elimi81** [comment]
I just looked into the code and I think the problem is in the [source.extension.vsixmanifest](https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Tooling/source.extension.vsixmanifest)-file

It has the line:
`<InstallationTarget Version="[11.0,16.0)" Id="Microsoft.VisualStudio.Community" />`

But according to [documentation](https://msdn.microsoft.com/en-us/library/hh696828(v=vs.140).aspx) the Id should be Microsoft.VisualStudio.Pro for Professional version etc. Do you agree?

**Comment by davidebbo** [comment]
But that may prevent it from installing on Community edition. I'm guessing we need to list multiple InstallationTarget. @pranavkm?

**Comment by pranavkm** [comment]
Pulling up random GitHub search for `InstallationTarget`, it seems like listing multiple is the way to go:

https://github.com/OlegPanagushin/NFX.HtmlEditor/blob/76a3b93568cc53a012a1a3ffeff654c327f7cad5/NFX.Markup/source.extension.vsixmanifest#L9-L14

That said, I haven't had issues installing it on copy of VS 2017 Enterprise. Maybe this is an issue with older versions of VS.

**Comment by davidebbo** [comment]
I guess let's add the line so we get a build, and @Elimi81 can give it a try? And obviously we'll need to make sure it doesn't regress current scenarios (not so likely).

**Comment by Elimi81** [comment]
Any update on this?

**Comment by davidebbo** [comment]
So what's the exact change we want to make here? @Elimi81 feel free to send a PR and we can get a build going that you can try.

Other option is that you can try using an older VSIX release from https://github.com/RazorGenerator/RazorGenerator/releases

**Comment by lukini** [comment]
I modified the vsix locally with a line for Microsoft.VisualStudio.Pro and I'm able to install it again.

**Comment by jaseporter01** [comment]
Using lukini's workaround as inspiration, I added these lines to get it to install to VS2013 Ultimate, VS2015 Enterprise and VS2017 Enterprise successfully:

  <Installation>
    <InstallationTarget Version="[11.0,16.0)" Id="Microsoft.VisualStudio.Community" />
    <InstallationTarget Version="[11.0,16.0)" Id="Microsoft.VisualStudio.Pro" />
    <InstallationTarget Version="[11.0,16.0)" Id="Microsoft.VisualStudio.Ultimate" />
    <InstallationTarget Version="[11.0,16.0)" Id="Microsoft.VisualStudio.Enterprise" />
  </Installation>
