### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by jeremyalan** [RazorGenerator/RazorGenerator#50]
I'm getting the following stack track when I try to compile my views:
```
Custom tool error: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Web.Razor.Parser.ParserContext.EndBlock()
   at System.Web.Razor.Utils.DisposableAction.Dispose(Boolean disposing)
   at System.Web.Razor.Utils.DisposableAction.Dispose()
   at System.Web.Razor.Parser.HtmlMarkupParser.ParseDocument()
   at System.Web.Razor.Parser.RazorParser.ParseCore(ITextDocument input)
   at System.Web.Razor.Parser.RazorParser.Parse(ITextDocument input)
   at System.Web.Razor.RazorTemplateEngine.GenerateCodeCore(ITextDocument input, String className, String rootNamespace, String sourceFileName, Nullable`1 cancelToken)
   at RazorGenerator.Core.RazorHost.GenerateCode()
```

When I remove all the Razor-specific tags `@RenderSection`, `RenderBody`, `@Styles.Render(...)`, etc., the compilation step seems to be working, but obviously without all the dynamic portions of the page.

I've tried removing all the Nuget packages from my solution, and doing a fresh package restore, re-installing the RazorGenerator VS extension (currently using v1.9.1), turning off Resharper, and restarted VS multiple times... running out of ideas.

Any thoughts?

**Comment by pranavkm** [comment]
Seems like a Razor bug. Do you see this error if you copy the page into a blank application that does not use RazorGenerator?

**Comment by jeremyalan** [comment]
Yes, it appears to be working without RazorGenerator.

I have multiple projects in my solution, and I'm attempting to share the Layout files between them to provide some consistency across the applications without copying code.  If I move the Layout file out of my shared project, and put it directly into one of the applications, it works as expected.

**Comment by jeremyalan** [comment]
I don't know if Nuget dependencies can cause conflicts with the VS extensions, but just in case, these are the package versions that I'm working with in my shared project:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net452" />
  <package id="CommonServiceLocator" version="1.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.Mvc.FixedDisplayModes" version="5.0.0" targetFramework="net452" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net452" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net452" />
  <package id="RazorGenerator.Mvc" version="2.3.6" targetFramework="net452" />
  <package id="structuremap" version="3.0.2.115" targetFramework="net452" />
  <package id="StructureMap.MVC4" version="3.0.2.115" targetFramework="net452" />
  <package id="WebActivator" version="1.5.1" targetFramework="net452" />
  <package id="WebActivatorEx" version="2.0.3" targetFramework="net452" />
  <package id="WebGrease" version="1.5.2" targetFramework="net452" />
</packages>
```
