### ISSUE TITLE
WriteAttribute/WriteAttributeTo NullPointerException

### ISSUE THREAD

**Issue by Tinkturianec** [RazorGenerator/RazorGenerator#57]
Hi,
I'm trying to use RazorGenerator for sharing view between asp.net and self hosted applications. If I set generator type to MvcHelper, like this:

```csharp
@* Generator: MvcHelper GeneratePrettyNames: true DisableLinePragmas: true *@

@helper Div(string color)
{
	<div style="background-color: @color">from helper</div>
}
```

and try use from my self hosted application direct or from another generated view, i receive exeptions:

>System.NullReferenceException: Object reference not set to an instance of an object.
>   at System.Web.WebPages.HelperPage.WriteAttributeTo(TextWriter writer, String name, PositionTagged\`1 prefix, PositionTagged\`1 suffix, AttributeValue[] values)
>   at RazorGeneratorTest.Views.Test.Helpers.<>c__DisplayClass1.&lt;Div>b__0(TextWriter __razor_helper_writer) in ...\BugReport\RazorGeneratorTest\RazorGeneratorTest\Views\Test\Helpers.generated.cs:line 0
>   at System.Web.WebPages.HelperResult.ToString()
>   at System.IO.TextWriter.WriteLine(Object value)
>   at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
>   at ConsoleApp.Program.Main() in ...\BugReport\RazorGeneratorTest\ConsoleApp\Program.cs:line 20

or

>System.NullReferenceException: Object reference not set to an instance of an object.
>   at System.Web.WebPages.HelperPage.WriteAttributeTo(TextWriter writer, String name, PositionTagged\`1 prefix, PositionTagged\`1 suffix, AttributeValue[] values)
>   at RazorGeneratorTest.Views.Test.Helpers.<>c__DisplayClass1.&lt;Div>b__0(TextWriter __razor_helper_writer) in ...\BugReport\RazorGeneratorTest\RazorGenerat
orTest\Views\Test\Helpers.generated.cs:line 0
>   at System.Web.WebPages.HelperResult.WriteTo(TextWriter writer)
>   at System.Web.WebPages.WebPageBase.Write(HelperResult result)
>   at RazorGeneratorTest.Views.Test.Helper.Execute() in ...\BugReport\RazorGeneratorTest\RazorGeneratorTest\Views\Test\Helper.generated.cs:line 49
>   at ConsoleApp.Program.PrintHtml(WebViewPage\`1 view, String color) in ...\BugReport\RazorGeneratorTest\ConsoleApp\Program.cs:line 37

If i use MvcView generator type and try call helper or all page Execute method like here:

```csharp
var view = new Standard {ViewData = {Model = "red"}};
view.PushContext(new WebPageContext(), new StringWriter());
view.Execute();
var result = view.Output.ToString();
view.PopContext();
```

for page:

```cshtml
@* Generator: MvcView GeneratePrettyNames: true DisableLinePragmas: true *@

@model string

@{
	Layout = null;
}

<div style="background-color: @Model;">Work!</div>
```

I receive exception in asp.net application:

>[NullReferenceException: Object reference not set to an instance of an object.]
>   System.Web.Mvc.WebViewPage.get_Context() +15
>   System.Web.WebPages.WebPageExecutingBase.WriteAttributeTo(String pageVirtualPath, TextWriter writer, String name, PositionTagged\`1 prefix, PositionTagged\`1 suffix, AttributeValue[] values) +469
>   System.Web.WebPages.WebPageExecutingBase.WriteAttributeTo(TextWriter writer, String name, PositionTagged\`1 prefix, PositionTagged\`1 suffix, AttributeValue[] values) +42
>   System.Web.WebPages.WebPageExecutingBase.WriteAttribute(String name, PositionTagged\`1 prefix, PositionTagged\`1 suffix, AttributeValue[] values) +40
>   RazorGeneratorTest.Views.Test.Standard.Execute() in d:\bulat\BugReport\RazorGeneratorTest\RazorGeneratorTest\Views\Test\Standard.generated.cs:48
>   RazorGeneratorTest.Controllers.TestController.MvcView() in d:\bulat\BugReport\RazorGeneratorTest\RazorGeneratorTest\Controllers\TestController.cs:25
>   lambda_method(Closure , ControllerBase , Object[] ) +62
>   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
>   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary\`2 parameters) +156
>   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary\`2 parameters) +27
>   System.Web.Mvc.Async.AsyncControllerActionInvoker.&lt;BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
>   System.Web.Mvc.Async.WrappedAsyncResult\`2.CallEndDelegate(IAsyncResult asyncResult) +29
>   System.Web.Mvc.Async.WrappedAsyncResultBase\`1.End() +49
>   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
>   System.Web.Mvc.Async.AsyncInvocationWithFilters.&lt;InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
>   System.Web.Mvc.Async.<>c__DisplayClass46.&lt;InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
>   System.Web.Mvc.Async.<>c__DisplayClass33.&lt;BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
>   System.Web.Mvc.Async.WrappedAsyncResult\`1.CallEndDelegate(IAsyncResult asyncResult) +10
>   System.Web.Mvc.Async.WrappedAsyncResultBase\`1.End() +49
   >System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
>   System.Web.Mvc.Async.<>c__DisplayClass2b.&lt;BeginInvokeAction>b__1c() +26
>   System.Web.Mvc.Async.<>c__DisplayClass21.&lt;BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
>   System.Web.Mvc.Async.WrappedAsyncResult\`1.CallEndDelegate(IAsyncResult asyncResult) +10
>   System.Web.Mvc.Async.WrappedAsyncResultBase\`1.End() +49
>   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
>   System.Web.Mvc.Controller.&lt;BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
>   System.Web.Mvc.Async.WrappedAsyncVoid\`1.CallEndDelegate(IAsyncResult asyncResult) +36
>   System.Web.Mvc.Async.WrappedAsyncResultBase\`1.End() +54
>   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +39
>   System.Web.Mvc.Controller.&lt;BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
>   System.Web.Mvc.Async.WrappedAsyncVoid\`1.CallEndDelegate(IAsyncResult asyncResult) +28
>   System.Web.Mvc.Async.WrappedAsyncResultBase\`1.End() +54
>   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
>   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
>   System.Web.Mvc.MvcHandler.&lt;BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
>   System.Web.Mvc.Async.WrappedAsyncVoid\`1.CallEndDelegate(IAsyncResult asyncResult) +36
>   System.Web.Mvc.Async.WrappedAsyncResultBase\`1.End() +54
>   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +31
>   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
>   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9650792
>   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

RazorGenerator version 1.9.1, VS Pro 2013.

Example solution: https://github.com/Tinkturianec/BugReport, controller Test

**Comment by cezarypiatek** [comment]
I have the same problem. After upgrading to RazorGenerator 1.10 and regenerating my helpers everything seems to be broken. In previous version of RazorGenerator views with directive Generator: MvcHelper was converted into static class, but now its a regular class that inherits from System.Web.WebPages.HelperPage. 

I see problem was reported by @Tinkturianec  over 2 moths ago. For me this is a serious issue. I cannot continue my development.  Where can I find old version of RazorGenerator VSIX ?

**Comment by davidebbo** [comment]
You can find older releases on https://github.com/RazorGenerator/RazorGenerator/releases

I think what happened is that the latest MVC/WebPages changed the way helpers are generated. It extending `System.Web.WebPages.HelperPage` is what the new model uses, so it is correct (that's why it doesn't cause any issues in the sample as discussed in #71). But if you're targeting an old framework, that may not agree with it.

Ideally, you should upgrade to latest MVC, but if that's not possible, you can try using an old VSIX build.

**Comment by cezarypiatek** [comment]
Thank you very much for link to older releases. I downgraded to version 1.9 and everything works fine.
As I said in #71  I was able to reproduce that issue with your sample application. Please try to run code from my last comment in #71 (I played with different version of MVC framework and there is no connection to that issue).

**Comment by davidebbo** [comment]
Yes, exposing old releases was overdue (I just published them). I'll make sure we always have them going forward.

I meant the **runtime** issue was not reproducible. Only the unit test part was, and that whole thing is in a rather poor state. See my last comment there.

**Comment by cezarypiatek** [comment]
Ok, now I understand the problem. I didn't run my application before  because of failed UT. So I need to find a way to fix my approach to UT. Thanks for your help @davidebbo

**Comment by k-best** [comment]
@davidebbo, Am I right, you create breaking change and do not fix it for year?
